services:
  - type: web
    name: swachdrishti-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_demo_data"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: swachdrishti-api.onrender.com
      - key: CORS_ALLOW_ALL
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: https://swachdrishti.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://swachdrishti.vercel.app,https://swachdrishti-api.onrender.com
      - key: FRONTEND_URL
        value: https://swachdrishti.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: SwachDrishti <onboarding@resend.dev>
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: SwachDrishti <swachdristi1010@gmail.com>
