# Generated by Django 6.1.1 on 2026-09-30 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('zone', models.CharField(default='Zone 1 - Central', max_length=100)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CITIZEN_VERIFIED', 'Citizen Verified'), ('REOPENED', 'Reopened')], default='REPORTED', max_length=30)),
                ('priority_score', models.FloatField(default=25.0)),
                ('priority_level', models.CharField(default='MEDIUM', max_length=20)),
                ('priority_factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='reports.wastecategory')),
                ('reports', models.ManyToManyField(blank=True, related_name='incidents', to='reports.wastereport')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('after_image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='reports.wastereport')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='incidents.incident')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
